title: Controlook - Sistema Online de Gestão para Igrejas
email: contato@controlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Controlook é um sistema online para organizar sua igreja
  com uma eficaz gestão financeira e controle dos membros
baseurl: "" # the subpath of your site, e.g. /blog
domain: "blog.controlook.com"
url: "https://blog.controlook.com" # the base hostname & protocol for your site, e.g. http://example.com
url_signup: "https://sys.controlook.com/signup/"
twitter_username: controlook
github_username: controlook
instagram_username: controlook
facebook_username: controlook

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

sass:
  style: compressed

permalink: pretty

paginate: 3

collections:
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      # path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      body_class: "interno"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scss
  - run.sh
  - bower.json
  - gruntfile.js
  - package.json
  - package-lock.json
